artshelf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from artshelf import settings
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls"))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('search/', views.catalog, name='search'),
    path('upload/', views.upload_product_view, name='upload_product'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('product/<slug:product_slug>/toggle-favorite/', views.toggle_favorite, name='toggle_favorite'),

]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('events/', views.events, name='events')
]

goods/models.py
from pyexpat import model
from unicodedata import category
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.utils.text import slugify
from unidecode import unidecode

# Create your models here.
class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")

    class Meta:
        db_table: str = 'category'
        verbose_name: str = 'Категория'
        verbose_name_plural: str = 'Категории'

    def __str__(self):
        return self.name

class Tags(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name="Название")

    class Meta:
        db_table: str = 'tag'
        verbose_name: str = 'Тэг'
        verbose_name_plural: str = 'Тэги'

    def __str__(self):
        return self.name

class Products(models.Model):
    title = models.CharField(max_length=150, unique=False, verbose_name="Название")
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name="URL")
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name="Изображение")
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name="Цена")
    category = models.ForeignKey(to=Categories, on_delete=models.PROTECT, verbose_name="Категория")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата публикации")
    is_available = models.BooleanField(default=True, verbose_name="В наличии")
    tags = models.ManyToManyField(Tags, blank=True, verbose_name="Тэги")
    size = models.CharField(max_length=50, unique=False, blank=True, verbose_name="Размер")
    material = models.CharField(max_length=150, blank=True, unique=False, verbose_name="Материал")
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='products',
        verbose_name='Пользователь',
        null=True,  # временно разрешаем пустые значения
        blank=True
    )

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(unidecode(self.title))
            unique_slug = base_slug
            counter = 1
            while Products.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{base_slug}-{counter}"
                counter += 1
            self.slug = unique_slug
        super().save(*args, **kwargs)

    class Meta:
        db_table: str = 'product'
        verbose_name: str = 'Продукт'
        verbose_name_plural: str = 'Продукты'
        ordering = ("id",)

    def __str__(self):
        return self.title

class Favorite(models.Model):
    user = models.ForeignKey(
        get_user_model(), 
        on_delete=models.CASCADE, 
        related_name='favorites', 
        verbose_name='Пользователь',
        null=True,  # временно разрешаем пустые значения
        blank=True
    )
    product = models.ForeignKey(
        Products, 
        on_delete=models.CASCADE, 
        related_name='favorited_by', 
        verbose_name='Продукт',
        null=True,  # временно разрешаем пустые значения
        blank=True
    )
    added_at = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'favorite'
        unique_together = ('user', 'product')
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные товары'

    def __str__(self):
        return f"{self.user.username} → {self.product.title}"

goods/forms.py
# forms.py
from django import forms
from .models import Products, Tags

class ProductForm(forms.ModelForm):
    tags = forms.CharField(required=False, help_text="Введите теги через запятую")

    class Meta:
        model = Products
        fields = ['title', 'description', 'image', 'price', 'category', 'is_available', 'size', 'material', 'tags']

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'form__input'
        self.fields['description'].widget.attrs['class'] = 'form__input'
        self.fields['price'].widget.attrs['class'] = 'form__input'
        self.fields['category'].widget.attrs['class'] = 'form__input'
        self.fields['size'].widget.attrs['class'] = 'form__input'
        self.fields['material'].widget.attrs['class'] = 'form__input'
        self.fields['tags'].widget.attrs['class'] = 'form__input'

goods/views.py
from urllib import request
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from goods.models import Products, Favorite, Categories, Tags
from goods.utils import q_search
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from .forms import ProductForm
from django.utils.text import slugify


def catalog(request):
    page = request.GET.get('page', 1) 
    order_by = request.GET.get('order_by', None) 
    query = request.GET.get('q', None) 

    category_ids = request.GET.getlist('categories')  # получаем id выбранных категорий
    if category_ids:
        products = Products.objects.filter(category__id__in=category_ids).distinct()
    elif query:
        products = q_search(query)
    else:
        products = Products.objects.all()

    if order_by and order_by != "default":
        products = products.order_by(order_by)

    categories = Categories.objects.all()  # чтобы отрисовать список в шаблоне

    paginator = Paginator(products, 40)
    current_page = paginator.page(int(page))

    context = {
        'products': current_page,
        'categories': categories,
        'selected_categories': list(map(int, category_ids)),  # для галочек в чекбоксах
    }
    return render(request, 'goods/catalog.html', context)


def product(request, product_slug):
    product = get_object_or_404(Products, slug=product_slug)
    favorite_products = []

    tags = product.tags.all

    if request.user.is_authenticated:
        favorite_products = Favorite.objects.filter(user=request.user).values_list('product_id', flat=True)

    return render(request, 'goods/product.html', {
        'product': product,
        'favorite_products': favorite_products,
        'tags': tags,
    })


@login_required
@require_POST
def toggle_favorite(request, product_slug):
    try:
        product = Products.objects.get(slug=product_slug)
    except Products.DoesNotExist:
        return JsonResponse({'error': 'Товар не найден'}, status=404)

    favorite, created = Favorite.objects.get_or_create(user=request.user, product=product)

    if not created:
        favorite.delete()
        return JsonResponse({'status': 'removed'})
    else:
        return JsonResponse({'status': 'added'})

@login_required
def upload_product_view(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.slug = slugify(form.cleaned_data['title'])
            product.user = request.user
            product.save()

            # Обработка тегов
            tags_str = form.cleaned_data.get('tags', '')
            tag_names = [t.strip().lower() for t in tags_str.split(',') if t.strip()]
            for name in tag_names:
                tag_obj, created = Tags.objects.get_or_create(name=name)
                product.tags.add(tag_obj)

            return redirect('catalog:product', product_slug=product.slug)
    else:
        form = ProductForm()

    return render(request, 'goods/upload_product.html', {'form': form})

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block content %}
<div class="products-block">
    <div class="content">
      <div class="block-bar">
        <h2 class="block-bar__title title">Популярные товары</h2>
      </div>
      <div class="products-block__content">
        <div class="products-block__popular">
          <a class="products-block__item products-block__main-item" href="#">
            <img src="{% static "deps/assets/dudka.png" %}" alt="">
          </a>
        </div>
        <div class="products-block__items">
          <a href="#" class="products-block__item">
            <img src="{% static "deps/assets/cat_in_lake_poster.webp" %}" alt="">
          </a>
          <a href="#" class="products-block__item">
            <img src="{% static "deps/assets/hang.jpg" %}" alt="">
          </a>
          <a href="#" class="products-block__item">
            <img src="{% static "deps/assets/birds.jpg" %}" alt="">
          </a>
          <a href="#" class="products-block__item">
            <img src="{% static "deps/assets/cat_flower.jpg" %}" alt="">
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="goods-block">
    <div class="content">
      <div class="block-bar">
        <h2 class="block-bar__title title hidden">Все товары</h2>
      </div>
      <div class="filters-bar">
        <button onclick="toggleMenu()" class="filters-bar__action active">
          <span class="filters-bar__icon material-symbols-outlined">filter_list</span> Фильтры
        </button>
        <form action=" {% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url 'catalog:index' %}{% endif %}" method="get" id="sortingForm">
          <div class="dropdown">
            <button class="filters-bar__action filters-bar__action--transparent" type="button">
              Сортировка <span class="filters-bar__icon material-symbols-outlined">keyboard_arrow_down</span>
            </button>
            {% for key, value in request.GET.items %}
              {% if key != 'order_by' and key != 'categories' %}
                <input type="hidden" name="{{ key }}" value="{{ value }}">
              {% endif %}
            {% endfor %}

            {% if request.GET.q %}
            <input type="hidden" name="q" value="{{ request.GET.q }}">
            {% endif %}

            <div class="dropdown-content">
              <div class="dropdown__item">
                <input type="radio" name="order_by" value="default" id="sortingradio1"
                  {% if not request.GET.order_by or request.GET.order_by == 'default' %}checked{% endif %}>
                <label for="sortingradio1">По умолчанию</label>
              </div>
              <div class="dropdown__item">
                <input type="radio" name="order_by" value="new" id="sortingradio2"
                  {% if request.GET.order_by == 'new' %}checked{% endif %}>
                <label for="sortingradio2">Новые</label>
              </div>
              <div class="dropdown__item">
                <input type="radio" name="order_by" value="price" id="sortingradio3"
                  {% if request.GET.order_by == 'price' %}checked{% endif %}>
                <label for="sortingradio3">От дешевых к дорогим</label>
              </div>
              <div class="dropdown__item">
                <input type="radio" name="order_by" value="-price" id="sortingradio4"
                  {% if request.GET.order_by == '-price' %}checked{% endif %}>
                <label for="sortingradio4">От дорогих к дешевым</label>
              </div>
            </div>
          </div>

      </div>
      <aside class="filter-menu" id="filterMenu">
        <div class="filter-menu__scroll">
          <div class="filter-menu__section">
            <h3 class="filter-menu__title">Тип продукции</h3>
            <ul class="filter-menu__categories">
              {% categories as categories %}
              {% for category in categories %}
              <li>
                <input type="checkbox" id="type{{ forloop.counter }}" name="categories" value="{{ category.id }}"
                {% if category.id in selected_categories %}checked{% endif %}>
                <label for="type{{ forloop.counter }}">{{ category.name }}</label>
              </li>
              {% endfor %}
            </ul>
          </div>
          <hr>
          <div class="filter-menu__section">
            <h3 class="filter-menu__title">Цена</h3>
            <div class="price-range">
              <input type="number" placeholder="от" min="0">
              <span>–</span>
              <input type="number" placeholder="до" min="0">
            </div>
          </div>
          <hr>
          <div class="filter-menu__section">
            <h3 class="filter-menu__title">Наличие</h3>
            <label>
              <input type="radio" name="availability">
              В наличии
            </label>
          </div>
          <button type="submit" class="button">Применить</button>
        </form>
        </div>
      </aside>
      <div class="goods-block__list">
        {% comment %} {% goods as goods %} {% endcomment %}
        {% for product in products %}
        <div class="card">
          <a class="card__cover" href="{% url "catalog:product" product.slug %}">
            {% if product.image %}
            <img src="{{ product.image.url }}" class="card__image-cover" alt="{{ product.title }}" />
            {% else %}
            <img src="{% static "deps/assets/image_not_found.png" %}" class="card__image-cover" />
            {% endif %}
          </a>
          <div class="card__info">
            <div class="card__content">
              <p class="card__title">
                {% autoescape off %}
                {% if product.headline %}{{product.headline}}{% else %}{{ product.title }}{% endif %}
                {% endautoescape %}
              </p>
              <a class="card__username" href="#">@{{product.user.username}}</a>
            </div>
            <div class="card__price">{{ product.price }}₽</div>
          </div>
        </div>
        {% empty %}
        <p>Нет товаров по выбранным категориям</p>
        {% endfor %}
      </div>
      <nav class="goods__pagination">
        <ul class="goods__pagination-list">
          <li class="goods__pagination-item">
            <a class="{% if not products.has_previous %}disabled{% endif %}" href="{% if products.has_previous %}?{% change_params page=products.previous_page_number %}
            {% else %}
            #
            {% endif %}
            ">Предыдущая</a>
          </li>

          {% for page in products.paginator.page_range %}
          <li class="goods__pagination-item">
            <a class="{% if products.number == page %}enabled{% endif %}" href="?{% change_params page=page %}">{{page}}</a>
          </li>
          {% endfor %}

          <li class="goods__pagination-item">
            <a class="{% if not products.has_next %}disabled{% endif %}" href="{% if products.has_next %}?{% change_params page=products.next_page_number %}
            {% else %}
            #
            {% endif %}
            ">Следующая</a>
          </li>
        </ul>
      </nav>
    </div>
  </div>
  <!-- JavaScript для открытия/закрытия меню -->
  <script>
    const filterMenu = document.getElementById("filterMenu");

    function toggleMenu() {
      filterMenu.classList.toggle("open");
    }

    document.addEventListener("click", function(event) {
      const isClickInside = filterMenu.contains(event.target);
      const isButton = event.target.closest(".filters-bar__action");

      if (!isClickInside && !isButton && filterMenu.classList.contains("open")) {
        filterMenu.classList.remove("open");
      }
    });

    // Автоотправка формы сортировки
      document.querySelectorAll('input[name="order_by"]').forEach(function(radio) {
        radio.addEventListener('change', function() {
          document.getElementById('sortingForm').submit();
        });
      });
  </script>
{% endblock content %}

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<main class="product-page">
    <div class="content">
        <div class="product-page__container">
            <nav class="product-page__breadcrumbs">
                <a href="{% url "main:index" %}">Главная</a> /
                <a href="{% url "catalog:index" %}">Каталог</a> /
                <span>{{product.title}}</span>
            </nav>
            <section class="product-page__content">
                <div class="product-page__gallery">
                    <div class="product-page__gallery-wrapper">
                        <img src="{{ product.image.url }}" alt="#" class="product-page__image-main"/>
                        <button class="product-favorite-btn {% if product.id in favorite_products %}active{% endif %}" data-product-slug="{{ product.slug }}">
                            <span class="material-symbols-outlined product-favorite-btn__icon">favorite</span>
                        </button>
                    </div>
                    <p class="product-page__date">Опубликовано 01.01.2025</p>
                </div>

                <div class="product-page__info">
                    <div class="product-page__title-container">
                        <h1 class="product-page__title">{{product.title}}</h1>
                        <p class="product-page__price">{{product.price}}₽</p>
                    </div>
                    <p class="product-page__category">{{product.category}}</p>
                    <ul class="product-page__tags">
                        {% for tag in tags %}
                        <li class="product-page__tag">{{ tag.name }}</li>
                        {% empty %}
                        <p class="product-page__description">
                        У товара нет тэгов.
                        </p>
                        {% endfor %}
                    </ul>

                    {% if product.description %}
                    <p class="product-page__description">
                        {{ product.description }}
                    </p>
                    {% else %}
                    <p class="product-page__description">
                        У товара нет описания.
                    </p>
                    {% endif %}

                    <ul class="product-page__details">
                        <hr>
                        <li>
                            <details class="product-page__details-item">
                                <summary class="product-page__details-title">РАЗМЕР</summary>
                                <div class="product-page__details-content">{{ product.size }}</div>
                            </details>
                        </li>
                        <hr>
                        <li>
                            <details class="product-page__details-item">
                                <summary class="product-page__details-title">МАТЕРИАЛ</summary>
                                <div class="product-page__details-content">{{ product.material }}</div>
                            </details>
                        </li>
                        <hr>
                        <li>
                            <details class="product-page__details-item">
                                <summary class="product-page__details-title">НАЛИЧИЕ</summary>
                                <div class="product-page__details-content">В наличии</div>
                            </details>
                        </li>
                        <hr>
                    </ul>

                    <div class="product-page__author">
                        <div class="product-page__author-info">
                            <p class="product-page__author-name">{{product.user.username}}</p>
                            <a class="product-page__contact-button button">Связаться</a>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</main>

{% endblock content %}

{% block script %}

<script>
    document.querySelectorAll('.product-favorite-btn').forEach(btn => {
        btn.addEventListener('click', function () {
            const productSlug = this.dataset.productSlug;
            const icon = this.querySelector('.product-favorite-btn__icon');

            fetch(`/catalog/product/${productSlug}/toggle-favorite/`, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': '{{ csrf_token }}',
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'added') {
                    this.classList.add('active');
                } else if (data.status === 'removed') {
                    this.classList.remove('active');
                }
            });
        });
    });
</script>


{% endblock script %}

goods/templates/goods/upload_product.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="form">
    <div class="form__container">
        <h2 class="form__title title">Загрузить товар</h2>
        <form method="POST" enctype="multipart/form-data" class="upload-form">
            {% csrf_token %}

            <label for="id_title">Название:</label>
            {{ form.title }}

            <label for="id_description">Описание:</label>
            {{ form.description }}

            <label for="id_image">Изображение:</label>
            {{ form.image }}

            <label for="id_price">Цена:</label>
            {{ form.price }}

            <label for="id_category">Категория:</label>
            {{ form.category }}

            <label for="id_is_available">В наличии:</label>
            {{ form.is_available }}

            <label for="id_size">Размер:</label>
            {{ form.size }}

            <label for="id_material">Материал:</label>
            {{ form.material }}

            <label for="id_tags">Теги (через запятую):</label>
            {{ form.tags }}

            <button class="form__button" type="submit">Опубликовать</button>
        </form>
    </div>
</div>
{% endblock content %}