artshelf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from artshelf import settings
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls"))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('search/', views.catalog, name='search'),
    path('upload/', views.upload_product_view, name='upload_product'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('product/<slug:product_slug>/toggle-favorite/', views.toggle_favorite, name='toggle_favorite'),

]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('events/', views.events, name='events')
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile_view, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.public_profile_view, name='public_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    city = models.CharField(blank=True, null=True, max_length=100, verbose_name="Город")
    is_popular = models.BooleanField(default=False)

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from dataclasses import fields
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User

class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "email",
            "username",
            "password1",
            "password2",
        )
    
    email = forms.CharField()
    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "image",
            "username",
            "description",
            "city")

    image = forms.ImageField(required=False)
    username = forms.CharField()
    description = forms.CharField()
    city = forms.CharField()

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['image'].widget.attrs['class'] = 'form__input'
        self.fields['username'].widget.attrs['class'] = 'form__input'
        self.fields['description'].widget.attrs['class'] = 'form__input'
        self.fields['city'].widget.attrs['class'] = 'form__input'

users/views.py
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login as auth_login
from users.forms import UserLoginForm, UserRegistrationForm, ProfileForm
from django.urls import reverse, reverse_lazy
from goods.models import Products 
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = UserLoginForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('main:index') 
    else:
        form = UserLoginForm()

    context = {
        'title': 'Авторизация',
        'form': form
    }
    return render(request, 'users/login.html', context)

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()


    context = {
        'title': 'Регистрация',
        'form': form
    }
    return render(request, 'users/registration.html', context)

def profile(request):
    context = {
    }
    return render(request, 'users/profile.html', context)

def logout(request):
    auth.logout(request)
    context = {
    }
    return redirect(reverse('main:index'))

# def profile_view(request):
#     user = request.user
#     user_products = Products.objects.filter(user=user)
#     return render(request, 'users/profile.html', {
#         'user_products': user_products
#     })

def profile_view(request):
    print('Текущий пользователь:', request.user.username)
    print('ID пользователя:', request.user.id)

    user_products = Products.objects.filter(user=request.user)
    print('Количество товаров:', user_products.count())

    # Избранные товары текущего пользователя
    favorite_products = Products.objects.filter(favorited_by__user=request.user)

    is_edit_mode = request.GET.get('edit') == 'true'

    if request.method == 'POST':
        form = ProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('user:profile')
    else:
        form = ProfileForm(instance=request.user)

    return render(request, 'users/profile.html', {
        'user_products': user_products,
        'favorite_products': favorite_products,
        'is_own_profile': True,
        'profile_user': request.user,  # чтобы шаблон отображал текущего пользователя
        'form': form,
        'edit_mode': is_edit_mode,
    })

def public_profile_view(request, username):
    profile_user = get_object_or_404(User, username=username)
    user_products = Products.objects.filter(user=profile_user)

    is_own_profile = request.user.is_authenticated and profile_user == request.user

    return render(request, 'users/profile.html', {
        'profile_user': profile_user,
        'user_products': user_products,
        'is_own_profile': is_own_profile,
    })

users/templates/users/edit.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="profile">
    <div class="profile__banner">
        <img src="{% static "deps/assets/chill-guy.png" %}" alt="">
    </div>
    <div class="content">
        <div class="profile__container">
            <div class="profile__info">
                <form action="{% url "users:profile" %}" method="post">
                    <div>
                        <img src="{% static "deps/assets/profile.jpg" %}" alt="Аватар пользователя" class="profile__icon">
                        <input type="file", id="id_image", name="image", accept="image/*">
                    </div>
                    <div>
                        <label for="id_username">Имя</label>
                        <input class="form__input" type="text" id="id_username" 
                        value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                        name="username" required
                        placeholder="Введите ваше имя пользователя">
                        {% if form.username.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
                        {% endif %}
                    </div>
                    {% comment %} <h3 class="profile__username">{{profile_user.username}}</h3> {% endcomment %}
                    <div>
                        <label for="id_description">Описание</label>
                        <input class="form__input" type="text" id="id_description" 
                        value="{% if form.description.value %}{{ form.description.value }}{% endif %}"
                        name="description" required
                        placeholder="Введите описание">
                    </div>
                    {% comment %} <p class="profile__description">{{profile_user.description}}</p> {% endcomment %}
                    <div>
                        <label for="id_city">Город</label>
                        <input class="form__input" type="text" id="id_city" 
                        value="{% if form.city.value %}{{ form.city.value }}{% endif %}"
                        name="city" required
                        placeholder="Введите ваш город">
                    </div>
                    <button type="submit" class="button">Сохранить</button>
                </form>
                {% comment %} <p class="profile__description"><span class="material-symbols-outlined">location_on</span>{{profile_user.city}}</p> {% endcomment %}
                <p class="profile__description"><span class="material-symbols-outlined">calendar_month</span>Аккаунт создан: {{profile_user.date_joined|date:"d.m.Y"}}</p>
            </div>
            <div class="profile__goods">
                <div class="profile__goods-buttons">
                    <ul class="profile__goods-buttons-switch">
                        <li class="profile__goods-buttons-switch-item">
                            <button class="profile__switch-button active">Публикации</button>
                        </li>
                        <li class="profile__goods-buttons-switch-item">
                            <button class="profile__switch-button">Избранное</button>
                        </li>
                    </ul>
                    {% if user.is_authenticated and profile_user == request.user%}
                    <button class="button">Редактировать профиль</button>
                    {% else %}
                    <button class="button">Подписаться</button>
                    {% endif %}
                </div>
                <div class="profile__goods-block__list" id="publications-block">
                    {% if user_products %}
                    {% for product in user_products %}
                    <div class="card">
                        <a class="card__cover" href="{% url "catalog:product" product.slug %}">
                            {% if product.image %}
                            <img src="{{ product.image.url }}" class="card__image-cover" alt="{{ product.title }}" />
                            {% else %}
                            <img src="{% static "deps/assets/image_not_found.png" %}" class="card__image-cover" />
                            {% endif %}
                        </a>
                        <div class="card__info">
                            <div class="card__content">
                                <p class="card__title">{{ product.title }}</p>
                                <a class="card__username" href="#">@{{ product.user.username }}</a>
                            </div>
                            <div class="card__price">{{ product.price }}₽</div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p class="no-products">У пользователя пока нет товаров.</p>
                    {% endif %}
                </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
<script>
</script>

{% endblock script %}

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<body>
    <div class="form">
        <div class="form__container">
            <h2 class="form__title title">Вход</h2>
            <form action="{% url "user:login" %}" method="post">
                {% csrf_token %}
                {% comment %} {% if form.non_field_errors %}
                <p>{{form.non_field_errors}}</p>
                {% endif %} {% endcomment %}
                <div class="form__item">
                    <label class="form__label" for="id_username">Введите имя:</label>
                    <input class="form__input" placeholder="Введите имя:" type="text"
                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                    name="username" 
                    id="id_username" required>
                </div>
                <div class="form__item">
                    <label class="form__label" for="id_password">Введите пароль:</label>
                    <input class="form__input" placeholder="Введите пароль:" type="password" 
                    id="id_password" 
                    name="password"required>
                </div>

                <a class="form__link" href="#">Забыли пароль?</a>

                <button class="form__button" type="submit">Войти в аккаунт</button>
            </form>
            <div class="form__link">
                Нет аккаунта? <a href="{% url "user:registration" %}">Зарегистрироваться</a>
            </div>
        </div>
    </div>
</body>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="profile">
    <div class="profile__banner">
        <img src="{% static "deps/assets/chill-guy.png" %}" alt="">
    </div>
    <div class="content">
        <div class="profile__container">
            <div class="profile__info">
                {% if edit_mode %}
                <form method="POST" enctype="multipart/form-data" class="profile__edit-form">
                    {% csrf_token %}
                    <div>
                        {% if user.image %}
                            <img src="{{ user.image.url }}" alt="" class="profile__icon">
                        {% else %}
                            <img src="{% static 'deps/assets/profile.jpg' %}" alt="" class="profile__icon">
                        {% endif %}
                        {{ form.avatar }}
                        <input type="file" class="" id="id_image"
                                    name='image'
                                    accept="image/*">
                    </div>
                    <div>
                        <label for="id_username">Имя пользователя:</label>
                        {{ form.username }} 
                    </div>
                    <div>
                        <label for="id_description">Описание:</label>
                        {{ form.description }}
                    </div>
                    <div>
                        <label for="id_city">Город:</label>
                        {{ form.city }}
                    </div>
                    <p class="profile__description">
                        <span class="material-symbols-outlined">calendar_month</span>
                        Аккаунт создан: {{ profile_user.date_joined|date:"d.m.Y" }}
                    </p>
                    <button type="submit" class="button save-button">Сохранить изменения</button>
                </form>
                {% else %}
                {% if user.image %}
                <img src="{{ user.image.url }}" alt="" class="profile__icon">
                {% else %}
                <img src="{% static 'deps/assets/profile.jpg' %}" alt="" class="profile__icon">
                {% endif %}
                <h3 class="profile__username">{{profile_user.username}}</h3>
                {% if profile_user.description %}
                <p class="profile__description">{{profile_user.description}}</p>
                {% endif %}
                {% if profile_user.city %}
                <p class="profile__description"><span class="material-symbols-outlined">location_on</span>{{profile_user.city}}</p>
                {% endif %}
                <p class="profile__description"><span class="material-symbols-outlined">calendar_month</span>Аккаунт создан: {{profile_user.date_joined|date:"d.m.Y"}}</p>
                {% endif %}
            </div>
            <div class="profile__goods">
                <div class="profile__goods-buttons">
                    <ul class="profile__goods-buttons-switch">
                        <li class="profile__goods-buttons-switch-item">
                            <button class="profile__switch-button active">Публикации</button>
                        </li>
                        <li class="profile__goods-buttons-switch-item">
                            <button class="profile__switch-button">Избранное</button>
                        </li>
                    </ul>
                    {% if is_own_profile %}
                        <a href="?edit=true" class="button">Редактировать профиль</a>
                    {% else %}
                        <button class="button">Подписаться</button>
                    {% endif %}
                </div>
                <div class="profile__goods-block__list" id="publications-block">
                    {% if user_products %}
                    {% for product in user_products %}
                    <div class="card">
                        <a class="card__cover" href="{% url "catalog:product" product.slug %}">
                            {% if product.image %}
                            <img src="{{ product.image.url }}" class="card__image-cover" alt="{{ product.title }}" />
                            {% else %}
                            <img src="{% static "deps/assets/image_not_found.png" %}" class="card__image-cover" />
                            {% endif %}
                        </a>
                        <div class="card__info">
                            <div class="card__content">
                                <p class="card__title">{{ product.title }}</p>
                                <a class="card__username" href="#">@{{ product.user.username }}</a>
                            </div>
                            <div class="card__price">{{ product.price }}₽</div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p class="no-products">У пользователя пока нет товаров.</p>
                    {% endif %}
                </div>
                <div class="profile__goods-block__list hidden" id="favorites-block">
                    {% if favorite_products %}
                        {% for product in favorite_products %}
                            <div class="card">
                        <a class="card__cover" href="{% url "catalog:product" product.slug %}">
                            {% if product.image %}
                            <img src="{{ product.image.url }}" class="card__image-cover" alt="{{ product.title }}" />
                            {% else %}
                            <img src="{% static "deps/assets/image_not_found.png" %}" class="card__image-cover" />
                            {% endif %}
                        </a>
                        <div class="card__info">
                            <div class="card__content">
                                <p class="card__title">{{ product.title }}</p>
                                <a class="card__username" href="#">@{{ product.user.username }}</a>
                            </div>
                            <div class="card__price">{{ product.price }}₽</div>
                        </div>
                    </div>
                        {% endfor %}
                    {% else %}
                        <p class="no-products">Избранных товаров пока нет.</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block script %}
<script>
    const switchButtons = document.querySelectorAll('.profile__switch-button');
    const publicationsBlock = document.getElementById('publications-block');
    const favoritesBlock = document.getElementById('favorites-block');

    switchButtons.forEach(button => {
        button.addEventListener('click', () => {
            switchButtons.forEach(btn => btn.classList.remove('active'));
            button.classList.add('active');

            if (button.textContent.trim() === 'Публикации') {
                publicationsBlock.classList.remove('hidden');
                favoritesBlock.classList.add('hidden');
            } else {
                publicationsBlock.classList.add('hidden');
                favoritesBlock.classList.remove('hidden');
            }
        });
    });

</script>

{% endblock script %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<body>
  <div class="form">
    <div class="form__container">
      <h2 class="form__title title">Регистрация</h2>
      <form action="{% url "user:registration" %}" method="post">
        {% csrf_token %}
        <div class="form__item">
          <label class="form__label" for="id_email">Введите email:</label>
          <input class="form__input" placeholder="Введите email:" type="email" id="id_email" 
          value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
          name="email" required>
          {% if form.email.errors %}
          <div class="alert alert-danger alert-dismissible fade show">{{form.email.errors}}</div>
          {% endif %}
        </div>

        <div class="form__item">
          <label class="form__label" for="id_username">Придумайте имя пользователя:</label>
          <input class="form__input" placeholder="Придумайте имя пользователя:" type="text" id="id_username" 
          value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
          name="username" required>
          {% if form.username.errors %}
          <div class="alert alert-danger alert-dismissible fade show">{{form.username.errors}}</div>
          {% endif %}
        </div>

        <div class="form__item">
          <label class="form__label" for="id_password1">Введите пароль:</label>
          <input class="form__input" placeholder="Введите пароль:" type="password" id="id_password1" 
          value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
          name="password1" required>
          {% if form.password1.errors %}
          <div class="alert alert-danger alert-dismissible fade show">{{form.password1.errors}}</div>
          {% endif %}
        </div>

        <div class="form__item">
          <label class="form__label" for="id_password2">Повторите пароль:</label>
          <input class="form__input" placeholder="Повторите пароль:" type="password" id="id_password2" 
          value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
          name="password2" required>
          {% if form.password2.errors %}
          <div class="alert alert-danger alert-dismissible fade show">{{form.password2.errors}}</div>
          {% endif %}
        </div>

        <div class="form__checkbox">
          <input type="checkbox" id="privacy" name="privacy" required>
          <label for="privacy">Я согласен с политикой обработки персональных данных и политикой конфиденциальности.</label>
        </div>

        <button class="form__button" type="submit">Создать аккаунт</button>
      </form>

      <div class="form__link">
        Уже есть аккаунт? <a href="{% url "user:login" %}">Войти</a>
      </div>
    </div>
  </div>
</body>
{% endblock content %}