artshelf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from artshelf import settings
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls"))
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('search/', views.catalog, name='search'),
    path('upload/', views.upload_product_view, name='upload_product'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('product/<slug:product_slug>/toggle-favorite/', views.toggle_favorite, name='toggle_favorite'),

]

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('authors/', views.authors, name='authors'),
    path('events/', views.events, name='events')
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profile/', views.profile_view, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('profile/<str:username>/', views.public_profile_view, name='public_profile'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>ArtShelf</title>
  <link href="{% static "deps/styles/normalize.css" %}" rel="stylesheet">
  <link href="{% static "deps/styles/style.css" %}" rel="stylesheet">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Ysabeau+SC:wght@1..1000&display=swap"
    rel="stylesheet">
  <link rel="stylesheet"
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
  {% block head %}
  {% endblock head %}
</head>

<body>
  <header class="header">
    <div class="header__container">
      <div class="header__item">
        <a href="{% url "main:index" %}"><img src="{% static "deps/assets/logo.png" %}" alt="Логотип artshelf" class="header__logo"></a>
      </div>
      <ul class="header__navigation">
        <li class="header__link">
          <a href="{% url "catalog:index" %}" class="header__button">Каталог</a>
        </li>
        <li class="header__link">
          <a href="{% url "main:authors" %}" class="header__button">Художники</a>
        </li>
        <li class="header__link">
          <a href="{% url "main:events" %}" class="header__button">Мероприятия</a>
        </li>
      </ul>
      <div class="header__item header__actions">
        <div class="search-bar">
          <span class="search-bar__icon material-symbols-outlined">search</span>
          <form role="search" action="{% url "catalog:search" %}" method="get">
            <input type="search" class="search-bar__input" aria-label="Search" placeholder="Поиск" name="q">
          </form>
          <div class="search-bar__filters">
            <button class="search-bar__filters-item active">Каталог</button>
            <button class="search-bar__filters-item">Художники</button>
            <button class="search-bar__filters-item">Мероприятия</button>
          </div>
        </div>
        <a href="{% url "catalog:upload_product" %}" class="header__button header__button--accent" style="margin-right: 21px;">Загрузить свой мерч</a>
        <a href="#" class="header__button header__button--circle">
          <span class="material-symbols-outlined">favorite</span>
        </a>
        {% if not user.is_authenticated %}
        <div class="account-menu">
          <a href="{% url "user:login" %}" class="header__button header__button--circle">
            <span class="material-symbols-outlined">account_circle</span>
          </a>
        {% elif user.is_admin or user.is_staff %}
        <div class="account-menu">
          <a href="#" class="header__button header__button--circle">
            <span class="material-symbols-outlined">account_circle</span>
          </a>
          <div class="menu-content">
            <a href="{% url 'user:logout' %}">Выйти</a>
            <a href="{% url 'admin:index' %}">Админ панель</a>
          </div>
        </div>
        {% else %}
        <div class="account-menu">
          <a href="{% url 'users:profile' %}" class="header__button header__button--circle">
            <span class="material-symbols-outlined">account_circle</span>
          </a>
          <div class="menu-content">
            <a href="{% url 'user:logout' %}">Выйти</a>
          </div>
        </div>
        {% endif %}
      </div>
    </div>
  </header>
{% include "includes/notifications.html" %}
{% block content %}
{% endblock content %}

  <footer class="footer">
    <div class="footer__container">
      <a href="{% url "main:index" %}"><img src="{% static "deps/assets/logo.png" %}" alt="Логотип artshelf" class="footer__logo"></a>
      <nav class="footer__navigation">
        <ul class="footer__navigation-list">
          <li class="footer__navigation-item"><a href="{% url "main:index" %}">Главная</a></li>
          <li class="footer__navigation-item"><a href="{% url "catalog:index" %}">Каталог</a></li>
          <li class="footer__navigation-item"><a href="{% url "main:authors" %}">Художники</a></li>
          <li class="footer__navigation-item"><a href="">Мероприятия</a></li>
        </ul>
        <ul class="footer__navigation-list">
          <li class="footer__navigation-item"><a href="">О нас</a></li>
          <li class="footer__navigation-item"><a href="">Политика конфиденциальности</a></li>
        </ul>
      </nav>
      <div class="footer__socials">
        <a href="" class="footer__socials-item"><img src="#" alt=""></a>
        <a href="" class="footer__socials-item"><img src="#" alt=""></a>
        <a href="" class="footer__socials-item"><img src="#" alt=""></a>
      </div>
    </div>
  </footer>
  {% block script %}
  {% endblock script %}
</body>

</html>